version: "3.8"

services:
  backend:
    build: .
    container_name: republica_facil_backend
    ports: 
     - "8000:8000"
    volumes: 
     - .:/backend

  db:
    image: postgres
    shm_size: 128mb
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: db_republica_facil
    ports:
      - "5433:5432"